#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "nord"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myspacevim#before"
    filetree_direction = "left"
    filemanager = "nerdtree"

[[layers]]
  name = "test"

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "smart"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "ui"
  enable_sidebar = false

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "default"

[[layers]]
  name = "git"

[[layers]]
  name = "vim"

[[layers]]
  name = "checkers"

[[layers]]
  name = "tools"

[[layers]]
  name = "tmux"

[[custom_plugins]]
  name = "tpope/vim-rails"
  on_event = ["BufNewFile", "BufRead"]

[[custom_plugins]]
  name = "tpope/vim-dispatch"

[[custom_plugins]]
  name = 'radenling/vim-dispatch-neovim'

[[custom_plugins]]
  name = 'ryanoasis/vim-devicons'
